### ISSUE TITLE
Ability to filter on derived attribute of the model

### ISSUE THREAD

**Issue by okarsono** [RIPAGlobal/scimitar#104] opened 2024-02-26 00:17 UTC
The `scim_attributes_map` mixin allows for a SCIM field to map to a custom method, such as this:

```ruby
   def scim_attributes_map
      {
        id: :id,
        username: :email,
        active: :active?  # active? is a method, not a persistent attribute stored in the model
      }
    end

    def active?
       ... # some complicated logic
    end
```

But it seems the `scim_queryable_attributes` mixin doesn't - it expects only columns of the model. If I want to filter on the active flag, I can't because `active?` or `active` is not a column that exists in my model.

I can't seem to figure out how to make this SCIM field queryable, ie something like this by the caller: `?filter=active eq true`

This doesnt work:
```
   def scim_queryable_attributes
      {
        active: { column: :active? }  # this doesn't work because active? is not a column
      }
    end
```

Is there anyway to make it work?

**Comment by richardvflux** [comment] 2024-02-26 01:58
It appears that Arel nodes don't work out of the box, I would have expected that they would?

e.g. 

`active: { column:  Arel.sql('if(deactivated_at is not null,true,false)') }`

**Comment by xjunior** [comment] 2024-02-28 14:03
@okarsono the queryable attributes map directly to the database. This is by design, and changing it would require deeper changes to the filtering strategies of this library. Perhaps you could add support to something like `active: { scope: :active }`?

@richardvflux they do not, but adding support to this shouldn't be too difficult. I believe this is a different issue from this one we're commenting on, though.

I suggest you download the code and hack it away. The maintainers of this lib do so for the sake of their work, so you'd be at the mercy of their priorities.

**Comment by pond** [comment] 2024-06-11 22:13
Closing this because, yes, there are two sides to it.

* Conceptually Scimitar would support non-ActiveRecord models and tries to keep the core class vs ActiveRecord class components separated, but it's not really a particularly well-tested use case.

* All the same, the attribute map part of its functionality is related to arbitrary classes, while the queryable attributes are tied to queryable database columns (via ORM class attributes) and, in the case when Simitar is auto-performing queries for you - doing so using ActiveRecord itself:

```
    # If using ActiveRecord support in Scimitar::Lists::QueryParser, the mapped
    # entities are columns and that's expressed in the names of keys described
    # below; if you have other approaches to searching, these might be virtual
    # attributes or other such constructs rather than columns. That would be up
    # to your non-ActiveRecord's implementation to decide.
```

 IDK what it'd look like to support _arbitrary_ queryable back-end plugins, but "more effort than it could possibly be worth" springs to mind 😅 but otherwise - a non-ActiveRecord implementation needs to handle queries itself, as Scimitar only provides ActiveRecord query generation.

**Closed by pond** 2024-06-11 22:13 UTC
